import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import React, { useState } from 'react';

export default function Home() {
	const router = useRouter();
	const [username, setUsername] = useState('');

	const handleChange = (e: React.FormEvent<HTMLInputElement>) =>
		setUsername(e.currentTarget.value);

	const handleSubmit = (e: React.SyntheticEvent) => {
		e.preventDefault();
		router.push({ pathname: '/user/[username]', query: { username } });
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<form onSubmit={handleSubmit}>
					<input
						type='text'
						value={username}
						onChange={handleChange}
					/>
				</form>
			</main>
		</div>
	);
}
